spring.application.name=to-do-list-project
# ???? ???????
server.port=${PORT:8080}

# ????????? ???? ??????
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate ?????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ?????????????? ???????? / ?????????? ?????? (??? ??????????)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ?????????? SQL ? ??????? (???????????, ??? ???????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true