spring.application.name=to-do-list-project
# ???? ???????
server.port=8080

# ????????? ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate ?????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ?????????????? ???????? / ?????????? ?????? (??? ??????????)
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL ? ??????? (???????????, ??? ???????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true